redmine_app:
    resource: "@RedmineAppBundle/Controller/"
    type:     annotation
dashboard:
    resource: "@RedmineAppBundle/Controller/Dashboard/"
    type:     annotation
    prefix:   "admin"
api:
    resource: "@RedmineAppBundle/Controller/Api/"
    type:     annotation
    prefix:   "api"

login_check:
    path: /login_check
logout:
    path: /logout
