security:

    encoders:
        Redmine\AppBundle\Entity\RedmineUser:
            algorithm: bcrypt
            cost: 12

    providers:
        dashboard:
            entity: {class: Redmine\AppBundle\Entity\RedmineUser, property: username }
#            id: redmine.userprovider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        api_area:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: redmine.api.security.apikeyauthenticator
            anonymous: false
        secured_area:
            pattern: ^/
            anonymous: ~
            simple_form:
                authenticator: redmine.form.authenticator
                provider: dashboard
                check_path:    login_check
                login_path:    login
                default_target_path: admin_user_home
                username_parameter: login_form[username]
                password_parameter: login_form[password]
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ROLE_USER] }
